version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    volumes:
      - ../outputs:/outputs
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ../outputs:/outputs
    depends_on:
      - redis

  worker:
    build:
      context: ./worker
      dockerfile: ../Dockerfile.worker
    env_file:
      - ../.env
    volumes:
      - ../outputs:/outputs
    depends_on:
      - backend
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
